### ISSUE TITLE
What's the khaos.yml for?

### ISSUE THREAD

**Issue by hhsnopek** [jstransformers/khaos-jstransformer#3]
I don't see it in any other templates or documentation for it (without passing it into the js api)

**Comment by RobLoach** [comment]
We've been using https://github.com/jstransformers/boilerplate primarily for new JSTransformers. I suggest you take a look at that instead.

Khaos.yml is for injecting metadata into the khaos configuration during generation:
https://github.com/segmentio/khaos/blob/682ee9a29bc0fa0d73aa51a821de94e13e5c70bc/bin/khaos-create#L18-L22

**Comment by hhsnopek** [comment]
awesome, thanks!
